////

= Shlaer-Mellor Days 2024 Session Planning

==== Session Types

All session types are eligible to be pre-recorded.  For pre-recorded
sessions, the presenter will be available live to respond to questions
and comments.

.Session Types
[%autowidth,options="header"]
|===
| Session Type           | Abbrev   |  #  |  time | Description
| keynote presentation   | keynote  |  1  | 30-60 | classic featured presentation from featured
                                                    expert
| technical presentation | tech     | 3-6 | 20-45 | These are traditional full length
                                                    presentations from recognized experts
                                                    in the field.  Together with the experience
                                                    reports, these represent the primary
                                                    content of the conference.
| experience report      | exprpt   | 0-4 | 10-30 | Experience reports are medium length
                                                    presentations focused on the application
                                                    of modeling in industry or education.
| panel discusion        | panel    | 0-2 | 10-30 | The panel discussion typically involves a
                                                    moderator and a panel of experts.  Questions
                                                    have been prepared and shared with panel
                                                    members.  Audience participation is included.
| debate                 | debate   | 0-1 | 10-30 | A debate doubles as a networking activity.
                                                    Participants are assigned to groups.  Each
                                                    group is given a position statement to debate.
                                                    After the debate time, summary statements
                                                    are presented by a moderator.
| networking activity    | network  | 2-4 |  5-30 | These activities are pre-arranged, potentially
                                                    moderated, topical and focused on connecting
                                                    participants.  Techniques to bridge local
                                                    and remote are to be prepared.
| interview              | iview    | 2-4 |  1-5  | interactive interview of person of interest
                                                    focusing on the role that makes the person
                                                    special to the xtUML community
| tool/app demonstration | demo     | 0-4 |  1-5  | demonstration of a new feature or procedure
                                                    in the tooling (ASL editor, Ciera,
                                                    OOA of MASL, canvas features, Carpark)
| company expo           | expo     | 0-4 |  1-5  | To showcase participant companies and
                                                    organizations, these will work best as
                                                    pre-recorded production videos.
| introduction           | intro    | <20 |  1-2  | personal introduction answering
                                                    a few key questions (name, profession,
                                                    organization, key connection with xtUML)
                                                    in a pre-recorded format
| video tour             | vtour    | 1-4 |  1-5  | 1-5 minute video tour of venue or point
                                                    of interest to the xtUML community
                                                    (Queens venue, Portsmouth, HMS Victory,
                                                    MatchBOX)
| happy hour             | hpyhour  | 0-1 | 20-40 | Happy hour is an organized tasting and
                                                    sharing of a beverage together.  It is
                                                    fun to have a brewmeister or distiller
                                                    present to explain and teach and connect
                                                    those participating online.
|===

////

==== Agenda

////
The columns in the table below are as follows:

* The first column labeled *T* is the minute count for the session.
* The second column labeled *Clock* is the target time of day (BST) for the session.
* Column three names to *Presenter*.
* The fourth column is a status flag.
* The fifth column contains an abbreviation for the *Type* of session as
  defined in Session Types.
* Column six gives a *Title* to the session if applicable.
////

**Please enjoy the video presentations on youtube by following the links in the agenda below.**

.Agenda
[%autowidth,options="header"]
|===
|  T | Clock | Presenter           | L | Title
|  5 | 13:00 | Cortland Starrett   | L | Welcome and Opening
|  5 | 13:05 | Michael Lee         | L | Shlaer-Mellor Day greeting and instructions
|  5 | 13:10 | John and Alasdar    | L | Background on Chess Challenge
| 15 | 13:25 | Colin Carter        | R | https://youtu.be/Lb8fStgOzPk[Chess Play Abstracted] 10
| 10 | 13:40 | mixing              | L | Mixing virtually - introductions
| 15 | 13:50 | Cortland Starrett   | R | https://youtu.be/AbRPBWrI7fY[Simple Max Advance] 10
|  5 | 14:05 |                     | L | 5-minute *break*
| 15 | 14:10 | John and Alasdar    | R | https://youtu.be/yybpt3GbOO8/[Pretty Smart Chess Model] 10
| 30 | 14:25 | Levi Starrett       | R | https://www.youtube.com/watch?v=24CFUk3dY1U/[Exploring the Future] 25
|  5 | 14:55 |                     | L | 5-minute *break*
| 25 | 15:00 | Cortland Starrett   | R | https://youtu.be/d4GSvtefbaM[Zero Duration Timer Idiom and CrossFit Cindy] 18
|  5 | 15:25 |                     | L | 5-minute *break*
| 20 | 15:30 | Levi Starrett       | R | https://www.youtube.com/watch?v=IuGVajg8vPI[2024 Chess Challenge Tournament Results] 12
| 20 | 15:50 | All                 | L | Tooling Update and Project Status
|  5 | 16:10 | Cort and Mike       | L | closing remarks
| 30 | 16:15 | Happy Hour          | L | favorite beverage
|===

Tooling Update:  log4cpp, textual persistence, asl2masl, self idiom, BridgePoint bug fixes

**Video Collection with Introductory Words**

Shlaer-Mellor Days 2024 Conference is in the books. We enjoyed 6
presentations along with mixing and debating and banter. The first
presentation was by Colin Carter who gave a tour of an abstract data model
of the game of chess. See it here: https://youtu.be/Lb8fStgOzPk[Chess Play Abstracted].

In the game of chess, what is the simplest strategy that might win? Can
the model be translated into C code? This presentation answers those
questions: https://youtu.be/AbRPBWrI7fY[Simple Max Advance]

We saw a basic strategy in Simple Max Advance. Now, John and Alasdar
present a Pretty Smart Chess Bot that aggressively takes the opponent's
pieces! https://youtu.be/yybpt3GbOO8/[Pretty Smart Chess Model]

The most in-depth treatment of Chess strategy was presented by Levi
Starrett in 'Exploring the Future'. Levi's model recursively played
hypothetical moves and counter-moves to discover the best next move. His
robot can beat other robots, people and even himself!
https://www.youtube.com/watch?v=24CFUk3dY1U/[Exploring the Future]

Arguably (pun intended) the presentation that sparked the most debate
during the 2024 Shlaer-Mellor Days conference was titled "Zero Duration
Timer Idiom and CrossFit Cindy". Cortland Starrett claimed to identify a
bug in the Shlaer-Mellor Method and proposed a fix as well as a
work-around (until the fix is agreed upon). And if you are a fitness nerd,
this is for you!
https://youtu.be/d4GSvtefbaM[Zero Duration Timer Idiom and CrossFit Cindy]

The final presentation of the 2024 Shlaer-Mellor Days conference included
the results of the Chess Modeling Challenge tournament. Using BridgePoint,
Levi Starrett built an executable model to run the challenge. This model
played each of the bots against one another in an Arena-Style tournament.
https://www.youtube.com/watch?v=IuGVajg8vPI[2024 Chess Challenge Tournament Results]

