
// = Shlaer-Mellor Days 2022 Session Planning

////

==== Session Types

All session types are eligible to be pre-recorded.  For pre-recorded
sessions, the presenter will be available live to respond to questions
and comments.

.Session Types
[%autowidth,options="header"]
|===
| Session Type           | Abbrev   |  #  |  time | Description
| keynote presentation   | keynote  |  1  | 30-60 | classic featured presentation from featured
                                                    expert
| technical presentation | tech     | 3-6 | 20-45 | These are traditional full length
                                                    presentations from recognized experts
                                                    in the field.  Together with the experience
                                                    reports, these represent the primary
                                                    content of the conference.
| experience report      | exprpt   | 0-4 | 10-30 | Experience reports are medium length
                                                    presentations focused on the application
                                                    of modeling in industry or education.
| panel discusion        | panel    | 0-2 | 10-30 | The panel discussion typically involves a
                                                    moderator and a panel of experts.  Questions
                                                    have been prepared and shared with panel
                                                    members.  Audience participation is included.
| debate                 | debate   | 0-1 | 10-30 | A debate doubles as a networking activity.
                                                    Participants are assigned to groups.  Each
                                                    group is given a position statement to debate.
                                                    After the debate time, summary statements
                                                    are presented by a moderator.
| networking activity    | network  | 2-4 |  5-30 | These activities are pre-arranged, potentially
                                                    moderated, topical and focused on connecting
                                                    participants.  Techniques to bridge local
                                                    and remote are to be prepared.
| interview              | iview    | 2-4 |  1-5  | interactive interview of person of interest
                                                    focusing on the role that makes the person
                                                    special to the xtUML community
| tool/app demonstration | demo     | 0-4 |  1-5  | demonstration of a new feature or procedure
                                                    in the tooling (ASL editor, Ciera,
                                                    OOA of MASL, canvas features, Carpark)
| company expo           | expo     | 0-4 |  1-5  | To showcase participant companies and
                                                    organizations, these will work best as
                                                    pre-recorded production videos.
| introduction           | intro    | <20 |  1-2  | personal introduction answering
                                                    a few key questions (name, profession,
                                                    organization, key connection with xtUML)
                                                    in a pre-recorded format
| video tour             | vtour    | 1-4 |  1-5  | 1-5 minute video tour of venue or point
                                                    of interest to the xtUML community
                                                    (Queens venue, Portsmouth, HMS Victory,
                                                    MatchBOX)
| happy hour             | hpyhour  | 0-1 | 20-40 | Happy hour is an organized tasting and
                                                    sharing of a beverage together.  It is
                                                    fun to have a brewmeister or distiller
                                                    present to explain and teach and connect
                                                    those participating online.
|===

////

==== Agenda (*DRAFT*)

The columns in the table below are as follows:

* The first column labeled *T* is the minute count for the session.
* The second column labeled *Clock* is the target time of day (GMT) for the session.
* Column three names to *Presenter*.
* The fourth column is a status flag.
* The fifth column contains an abbreviation for the *Type* of session as
  defined in Session Types.
* Column six gives a *Title* to the session if applicable.

.Agenda (*DRAFT* timings not confirmed)
[%autowidth,options="header"]
|===
|  T | Clock | Presenter           | L | Type    | Title
|  5 | 10:00 | Cortland Starrett   | L | live    | Welcome and Opening
|  5 | 00:00 | Michael Lee         | L | live    | Shlaer-Mellor Day greeting and instructions
| 20 | 00:00 | Paul and Colin      | R | tech    | State- and Data- centric Protocol Modelling
| 10 | 00:00 |                     | L | network | Mixing virtually - introductions
| 15 | 00:00 | Michael Lee         | R | tech    | Update on Shlaer-Mellor Commons
| 20 | 00:00 | John and Alasdar    | R | exprpt  | Populating Roadway Models using Model-to-Model Transformations
|  5 | 00:00 |                     | L | live    | 5-minute *break*
| 20 | 00:00 | Levi Starrett       | R | tech    | Textual xtUML
| 15 | 00:00 | Allan Kennedy       | R | tech    | JSON Domain
| 10 | 00:00 | Annie Allen         | R | live    | MC-Ada and ASL-to-MASL
| 20 | 00:00 |                     | L | network | virtually connected *LUNCH* - introductions
| 20 | 00:00 | Cortland Starrett   | R | tech    | Relationship Formalization and Referential Attributes
| 20 | 00:00 | Nils Paulsson       | R | tech    | Distributed Bridging
|  5 | 00:00 |                     | L | live    | 5-minute *break*
| 10 | 00:00 | Clive Boughton      | R | tech    | Shlaer-Mellor in MBSE
| 15 | 00:00 | all                 | L | exprpt  | Around-the-Table Status Updates
|  5 | 00:00 | Cort and Mike       | L | live    | closing remarks
| 30 | 00:00 | Happy Hour          | L | hpyhour | favorite beverage
|===


