asciidoctor ./bp_jumpstart/index.adoc -o ./bp_jumpstart/index.html
#asciidoctor ./docs/xday.adoc -o ./docs/xday.html
asciidoctor ./xtuml-class/class-prep/connect_shared_folders.adoc -o ./xtuml-class/class-prep/connect_shared_folders.html
asciidoctor ./xtuml-class/class-prep/index.adoc -o ./xtuml-class/class-prep/index.html
asciidoctor ./xtuml-class/crypto.adoc -o ./xtuml-class/crypto.html
asciidoctor ./xtuml-class/sumo_edit/sumo_create5.adoc -o ./xtuml-class/sumo_edit/sumo_create5.html
asciidoctor ./xtuml-class/sumo_edit/sumo_create4.adoc -o ./xtuml-class/sumo_edit/sumo_create4.html
asciidoctor ./xtuml-class/sumo_edit/sumo_create3.adoc -o ./xtuml-class/sumo_edit/sumo_create3.html
asciidoctor ./xtuml-class/sumo_edit/sumo_create2.adoc -o ./xtuml-class/sumo_edit/sumo_create2.html
asciidoctor ./xtuml-class/sumo_edit/sumo_create1.adoc -o ./xtuml-class/sumo_edit/sumo_create1.html
asciidoctor ./xtuml-class/sumo_edit/index.adoc -o ./xtuml-class/sumo_edit/index.html
asciidoctor ./xtuml-class/sumo_start.adoc -o ./xtuml-class/sumo_start.html
asciidoctor ./xtuml-class/sumo_project/index.adoc -o ./xtuml-class/sumo_project/index.html
asciidoctor ./xtuml-class/homework/1.4.adoc -o ./xtuml-class/homework/1.4.html
asciidoctor ./xtuml-class/homework/1.5.adoc -o ./xtuml-class/homework/1.5.html
asciidoctor ./xtuml-class/homework/ev3_setup.adoc -o ./xtuml-class/homework/ev3_setup.html
asciidoctor ./xtuml-class/homework/1.2.adoc -o ./xtuml-class/homework/1.2.html
asciidoctor ./xtuml-class/homework/1.3.adoc -o ./xtuml-class/homework/1.3.html
asciidoctor ./xtuml-class/homework/1.0.adoc -o ./xtuml-class/homework/1.0.html
asciidoctor ./xtuml-class/homework/build_balancer.adoc -o ./xtuml-class/homework/build_balancer.html
asciidoctor ./xtuml-class/homework/1.1.adoc -o ./xtuml-class/homework/1.1.html
asciidoctor ./xtuml-class/homework/index.adoc -o ./xtuml-class/homework/index.html
asciidoctor ./xtuml-class/index.adoc -o ./xtuml-class/index.html
asciidoctor ./balancer/index.adoc -o ./balancer/index.html
asciidoctor ./sumo/index.adoc -o ./sumo/index.html
asciidoctor ./index.adoc -o ./index.html
