= Welcome to xtUML Class Homework!
include::../../include.adoc[]

== Homework Assignments

=== Links to Assignements

* link:1.0{outfilesuffix}[Homework 1.0 - Introductions] due {duedatehw1_0}

* link:1.1{outfilesuffix}[Homework 1.1 - Support Accounts] due {duedatehw1_1}

* link:1.2{outfilesuffix}[Homework 1.2 - BridgePoint] due {duedatehw1_2}

* link:1.3{outfilesuffix}[Homework 1.3 - github setup] due {duedatehw1_3}

* link:1.4{outfilesuffix}[Homework 1.4 - Build the Robot] due {duedatehw1_4}

* link:1.5{outfilesuffix}[Homework 1.5 - Remote Desktop] due {duedatehw1_5}

* link:build_balancer{outfilesuffix}[Build the Balancer Robot (extra credit)] due {duedatebalancer}

* link:ev3_setup{outfilesuffix}[Set up EV3RT Dev Environment] due {duedateev3rt}


=== Pre-Grade Policy

受講者は、予備単位を取るために宿題を期日前に提出してください。Students may submit homework before the due date to receive a _pre-grade_.
予備単位は、単位張には記録されません。講師は時間が許せば　The pre-grade is not recorded in the grade book.  If time is available,
みなさんの宿題をみて返事をします。　the instructor will review the homework assignment and provide feedback
宿題が完璧なら、そう言いますし、問題があるならto the student.  If the homework is perfect, the instructor will say so.
最初に見つけた問題について指摘をします。If there is a problem, the instructor will inform the student of the
受講者は、それについて訂正を行って _first_ problem discovered in the homework.  Students may then correct
当初に指示された期日に投稿してください。the homework and submit at the normal due date.

予備単位として受け付けられるためには、宿題提出をTo be eligible for pre-grade, homework must be submitted more than one
期日の丸一日前までに行ってください。full day before the due date.

// Navigate upwards to the default index file.
link:../[XTUMLトレーニングクラスへ戻る]
