= Welcome to xtUML Class Homework!
include::../../include.adoc[]

== Home Assignments

=== Links to Assignements

* link:1.0.adoc[Homework 1.0 - Introductions] due 19 Sep 2018

* link:1.1.adoc[Homework 1.1 - Support Accounts] due 21 Sep 2018

* link:1.2.adoc[Homework 1.2 - BridgePoint] due 24 Sep 2018

* link:1.3.adoc[Homework 1.3 - github setup] due 26 Sep 2018

* link:1.4.adoc[Homework 1.4 - Build the Robot] due 28 Sep 2018

* link:1.5.adoc[Homework 1.5 - Remote Desktop] due 1 Oct 2018

* link:build_balancer.adoc[Build the Balancer Robot (extra credit)] due 1 Oct 2018  

* link:ev3_setup.adoc[Set up EV3RT Dev Environment] due 2 Oct 2018  


=== Pre-Grade Policy

Students may submit homework before the due date to receive a _pre-grade_.
The pre-grade is not recorded in the grade book.  If time is available,
the instructor will review the homework assignment and provide feedback
to the student.  If the homework is perfect, the instructor will say so.
If there is a problem, the instructor will inform the student of the
_first_ problem discovered in the homework.  Students may then correct
the homework and submit at the normal due date.

To be eligible for pre-grade, homework must be submitted more than one
full day before the due date.

link:../[Back to class home]
