= Welcome to xtUML Class Homework!
include::../../include.adoc[]

== Homework Assignments

=== Links to Assignements

* link:1.0{outfilesuffix}[Homework 1.0 - Introductions] due {duedatehw1_0}

* link:1.1{outfilesuffix}[Homework 1.1 - Support Accounts] due {duedatehw1_1}

* link:1.2{outfilesuffix}[Homework 1.2 - BridgePoint] due {duedatehw1_2}

* link:1.3{outfilesuffix}[Homework 1.3 - github setup] due {duedatehw1_3}

* link:1.4{outfilesuffix}[Homework 1.4 - Build the Robot] due {duedatehw1_4}

* link:1.5{outfilesuffix}[Homework 1.5 - Remote Desktop] due {duedatehw1_5}

* link:build_balancer{outfilesuffix}[Build the Balancer Robot (extra credit)] due {duedatebalancer}

* link:ev3_setup{outfilesuffix}[Set up EV3RT Dev Environment] due {duedateev3rt}


=== Pre-Grade Policy

Students may submit homework before the due date to receive a _pre-grade_.
The pre-grade is not recorded in the grade book.  If time is available,
the instructor will review the homework assignment and provide feedback
to the student.  If the homework is perfect, the instructor will say so.
If there is a problem, the instructor will inform the student of the
_first_ problem discovered in the homework.  Students may then correct
the homework and submit at the normal due date.

To be eligible for pre-grade, homework must be submitted more than one
full day before the due date.

link:../[Back to class home]
